convert_to_html:
  description: "Take the provided markdown text, which contains an analysis of SEC filings, and convert it into a well-structured 
                block of raw HTML. The output should only be the HTML body content (e.g., h3, p, ul, strong tags), not a full HTML document."
  expected_output: "A string containing only the HTML representation of the markdown content's body.
                 For example: '<h3>Analysis...</h3><p><strong>Key Findings:</strong>...</p>...'"

style_html_page:
  description: "Take the raw HTML block from the previous task and embed it into a complete, beautifully styled HTML5 document. 
                You must create a full HTML page with a head and body. Use Tailwind CSS (loaded from a CDN) to style the page.
                 The design should be professional, modern, and easy to read, with a clean layout, good typography, and appropriate spacing.
                  The final output must be a single string containing the entire HTML document."
  expected_output: "A single string containing a complete, well-formed HTML document (from <!DOCTYPE html> to </html>).
                 The document must include a <head> with a link to the Tailwind CSS CDN and a 
                 styled <body> that wraps the provided HTML content in a visually appealing layout. 
                 The final output MUST BE ONLY the HTML code."

